import type { ProCheckItem } from './types';
export const evidenceItems: ProCheckItem[] = [
  {
    id: 'PE01',
    number: 37,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'mechanical',
    prompt: 'question.PE01.prompt',
    helper: 'question.PE01.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE01.option.not-yet.label',
        feedback: 'question.PE01.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE01.option.guided.label',
        feedback: 'question.PE01.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE01.option.contributed.label',
        feedback: 'question.PE01.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE01.option.verified.label',
        feedback: 'question.PE01.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE02',
    number: 38,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'mechanical',
    prompt: 'question.PE02.prompt',
    helper: 'question.PE02.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE02.option.not-yet.label',
        feedback: 'question.PE02.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE02.option.guided.label',
        feedback: 'question.PE02.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE02.option.contributed.label',
        feedback: 'question.PE02.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE02.option.verified.label',
        feedback: 'question.PE02.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE03',
    number: 39,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'cad',
    prompt: 'question.PE03.prompt',
    helper: 'question.PE03.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE03.option.not-yet.label',
        feedback: 'question.PE03.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE03.option.guided.label',
        feedback: 'question.PE03.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE03.option.contributed.label',
        feedback: 'question.PE03.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE03.option.verified.label',
        feedback: 'question.PE03.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE04',
    number: 40,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'cad',
    prompt: 'question.PE04.prompt',
    helper: 'question.PE04.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE04.option.not-yet.label',
        feedback: 'question.PE04.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE04.option.guided.label',
        feedback: 'question.PE04.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE04.option.contributed.label',
        feedback: 'question.PE04.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE04.option.verified.label',
        feedback: 'question.PE04.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE05',
    number: 41,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'fabrication',
    prompt: 'question.PE05.prompt',
    helper: 'question.PE05.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE05.option.not-yet.label',
        feedback: 'question.PE05.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE05.option.guided.label',
        feedback: 'question.PE05.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE05.option.contributed.label',
        feedback: 'question.PE05.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE05.option.verified.label',
        feedback: 'question.PE05.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE06',
    number: 42,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'fabrication',
    prompt: 'question.PE06.prompt',
    helper: 'question.PE06.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE06.option.not-yet.label',
        feedback: 'question.PE06.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE06.option.guided.label',
        feedback: 'question.PE06.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE06.option.contributed.label',
        feedback: 'question.PE06.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE06.option.verified.label',
        feedback: 'question.PE06.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE07',
    number: 43,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'electronics',
    prompt: 'question.PE07.prompt',
    helper: 'question.PE07.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE07.option.not-yet.label',
        feedback: 'question.PE07.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE07.option.guided.label',
        feedback: 'question.PE07.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE07.option.contributed.label',
        feedback: 'question.PE07.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE07.option.verified.label',
        feedback: 'question.PE07.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE08',
    number: 44,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'electronics',
    prompt: 'question.PE08.prompt',
    helper: 'question.PE08.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE08.option.not-yet.label',
        feedback: 'question.PE08.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE08.option.guided.label',
        feedback: 'question.PE08.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE08.option.contributed.label',
        feedback: 'question.PE08.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE08.option.verified.label',
        feedback: 'question.PE08.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE09',
    number: 45,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'programming',
    prompt: 'question.PE09.prompt',
    helper: 'question.PE09.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE09.option.not-yet.label',
        feedback: 'question.PE09.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE09.option.guided.label',
        feedback: 'question.PE09.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE09.option.contributed.label',
        feedback: 'question.PE09.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE09.option.verified.label',
        feedback: 'question.PE09.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE10',
    number: 46,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'programming',
    prompt: 'question.PE10.prompt',
    helper: 'question.PE10.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE10.option.not-yet.label',
        feedback: 'question.PE10.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE10.option.guided.label',
        feedback: 'question.PE10.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE10.option.contributed.label',
        feedback: 'question.PE10.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE10.option.verified.label',
        feedback: 'question.PE10.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE11',
    number: 47,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'physicalComputing',
    prompt: 'question.PE11.prompt',
    helper: 'question.PE11.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE11.option.not-yet.label',
        feedback: 'question.PE11.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE11.option.guided.label',
        feedback: 'question.PE11.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE11.option.contributed.label',
        feedback: 'question.PE11.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE11.option.verified.label',
        feedback: 'question.PE11.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE12',
    number: 48,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'physicalComputing',
    prompt: 'question.PE12.prompt',
    helper: 'question.PE12.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE12.option.not-yet.label',
        feedback: 'question.PE12.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE12.option.guided.label',
        feedback: 'question.PE12.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE12.option.contributed.label',
        feedback: 'question.PE12.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE12.option.verified.label',
        feedback: 'question.PE12.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE13',
    number: 49,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'sensorsIot',
    prompt: 'question.PE13.prompt',
    helper: 'question.PE13.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE13.option.not-yet.label',
        feedback: 'question.PE13.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE13.option.guided.label',
        feedback: 'question.PE13.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE13.option.contributed.label',
        feedback: 'question.PE13.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE13.option.verified.label',
        feedback: 'question.PE13.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE14',
    number: 50,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'sensorsIot',
    prompt: 'question.PE14.prompt',
    helper: 'question.PE14.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE14.option.not-yet.label',
        feedback: 'question.PE14.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE14.option.guided.label',
        feedback: 'question.PE14.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE14.option.contributed.label',
        feedback: 'question.PE14.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE14.option.verified.label',
        feedback: 'question.PE14.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE15',
    number: 51,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'aiVision',
    prompt: 'question.PE15.prompt',
    helper: 'question.PE15.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE15.option.not-yet.label',
        feedback: 'question.PE15.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE15.option.guided.label',
        feedback: 'question.PE15.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE15.option.contributed.label',
        feedback: 'question.PE15.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE15.option.verified.label',
        feedback: 'question.PE15.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE16',
    number: 52,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'aiVision',
    prompt: 'question.PE16.prompt',
    helper: 'question.PE16.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE16.option.not-yet.label',
        feedback: 'question.PE16.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE16.option.guided.label',
        feedback: 'question.PE16.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE16.option.contributed.label',
        feedback: 'question.PE16.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE16.option.verified.label',
        feedback: 'question.PE16.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE17',
    number: 53,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'integration',
    prompt: 'question.PE17.prompt',
    helper: 'question.PE17.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE17.option.not-yet.label',
        feedback: 'question.PE17.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE17.option.guided.label',
        feedback: 'question.PE17.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE17.option.contributed.label',
        feedback: 'question.PE17.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE17.option.verified.label',
        feedback: 'question.PE17.option.verified.feedback',
      },
    ],
  },
  {
    id: 'PE18',
    number: 54,
    phase: 'proEvidence',
    kind: 'proCheck',
    area: 'integration',
    prompt: 'question.PE18.prompt',
    helper: 'question.PE18.helper',
    options: [
      {
        id: 'not-yet',
        value: 1,
        label: 'question.PE18.option.not-yet.label',
        feedback: 'question.PE18.option.not-yet.feedback',
      },
      {
        id: 'guided',
        value: 2,
        label: 'question.PE18.option.guided.label',
        feedback: 'question.PE18.option.guided.feedback',
      },
      {
        id: 'contributed',
        value: 3,
        label: 'question.PE18.option.contributed.label',
        feedback: 'question.PE18.option.contributed.feedback',
      },
      {
        id: 'verified',
        value: 4,
        label: 'question.PE18.option.verified.label',
        feedback: 'question.PE18.option.verified.feedback',
      },
    ],
  },
];
