/** Specific, low-stakes practice suggestions, not prescriptions or rankings. */
export const growthActions: Record<string, string> = {
  problem: 'growthAction.problem',
  planning: 'growthAction.planning',
  collaboration: 'growthAction.collaboration',
  handsOn: 'growthAction.handsOn',
  design: 'growthAction.design',
  pitch: 'growthAction.pitch',
  mechanical: 'growthAction.mechanical',
  cad: 'growthAction.cad',
  fabrication: 'growthAction.fabrication',
  electronics: 'growthAction.electronics',
  programming: 'growthAction.programming',
  physicalComputing: 'growthAction.physicalComputing',
  sensorsIot: 'growthAction.sensorsIot',
  aiVision: 'growthAction.aiVision',
  integration: 'growthAction.integration',
  unfamiliarTools: 'growthAction.unfamiliarTools',
  'not-sure': 'growthAction.not-sure',
};
