import type { AssessmentItem, AssessmentVersion } from './types';

export const assessmentVersion: AssessmentVersion = 'standard-v1.8';

export const behaviourScale = {
  prompt: 'scale.behaviour.prompt',
  low: 'scale.behaviour.low',
  high: 'scale.behaviour.high',
  details: [
    'scale.behaviour.details.0',
    'scale.behaviour.details.1',
    'scale.behaviour.details.2',
    'scale.behaviour.details.3',
    'scale.behaviour.details.4',
  ],
};

export const technicalScale = {
  prompt: 'scale.technical.prompt',
  low: 'scale.technical.low',
  high: 'scale.technical.high',
  details: [
    'scale.technical.details.0',
    'scale.technical.details.1',
    'scale.technical.details.2',
    'scale.technical.details.3',
    'scale.technical.details.4',
  ],
};

const projectCountOptions = [
  { id: 'none', label: 'projectCount.none.label', value: 1 },
  { id: 'one', label: 'projectCount.one.label', value: 2 },
  { id: 'two', label: 'projectCount.two.label', value: 3 },
  { id: 'three-four', label: 'projectCount.three-four.label', value: 4 },
  { id: 'five-plus', label: 'projectCount.five-plus.label', value: 5 },
];

const responsibilityOptions = [
  { id: 'observed', label: 'responsibility.observed.label', value: 1 },
  {
    id: 'guided',
    label: 'responsibility.guided.label',
    value: 2,
  },
  {
    id: 'owned-familiar',
    label: 'responsibility.owned-familiar.label',
    value: 3,
  },
  {
    id: 'owned-subsystem',
    label: 'responsibility.owned-subsystem.label',
    value: 4,
  },
  {
    id: 'integrated',
    label: 'responsibility.integrated.label',
    value: 5,
  },
];

export const interestOptions = [
  { id: 'built-environment', label: 'interest.built-environment.label' },
  { id: 'robotics', label: 'interest.robotics.label' },
  { id: 'product-design', label: 'interest.product-design.label' },
  { id: 'connected-devices', label: 'interest.connected-devices.label' },
  { id: 'software', label: 'interest.software.label' },
  { id: 'data-ai', label: 'interest.data-ai.label' },
  { id: 'energy', label: 'interest.energy.label' },
  { id: 'health', label: 'interest.health.label' },
  { id: 'operations', label: 'interest.operations.label' },
  { id: 'other-interest', label: 'interest.other-interest.label' },
];

export const growthOptions = [
  { id: 'problem', label: 'growth.problem.label' },
  { id: 'planning', label: 'growth.planning.label' },
  { id: 'collaboration', label: 'growth.collaboration.label' },
  { id: 'handsOn', label: 'growth.handsOn.label' },
  { id: 'design', label: 'growth.design.label' },
  { id: 'pitch', label: 'growth.pitch.label' },
  { id: 'mechanical', label: 'growth.mechanical.label' },
  { id: 'cad', label: 'growth.cad.label' },
  { id: 'fabrication', label: 'growth.fabrication.label' },
  { id: 'electronics', label: 'growth.electronics.label' },
  { id: 'programming', label: 'growth.programming.label' },
  { id: 'physicalComputing', label: 'growth.physicalComputing.label' },
  { id: 'sensorsIot', label: 'growth.sensorsIot.label' },
  { id: 'aiVision', label: 'growth.aiVision.label' },
  { id: 'integration', label: 'growth.integration.label' },
  {
    id: 'unfamiliarTools',
    label: 'growth.unfamiliarTools.label',
  },
  { id: 'not-sure', label: 'growth.not-sure.label' },
];

export const questions: AssessmentItem[] = [
  {
    id: 'B01',
    number: 1,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'problem',
    prompt: 'question.B01.prompt',
    activeLearningEssentialTags: ['problemSolving'],
  },
  {
    id: 'B02',
    number: 2,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'collaboration',
    prompt: 'question.B02.prompt',
    activeLearningEssentialTags: ['valueAndAttitude'],
  },
  {
    id: 'B03',
    number: 3,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'pitch',
    prompt: 'question.B03.prompt',
    activeLearningEssentialTags: ['communication'],
  },
  {
    id: 'B04',
    number: 4,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'planning',
    prompt: 'question.B04.prompt',
    activeLearningEssentialTags: ['problemSolving', 'designAndInnovation'],
  },
  {
    id: 'B05',
    number: 5,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'design',
    prompt: 'question.B05.prompt',
    activeLearningEssentialTags: ['designAndInnovation', 'lifelongLearning'],
  },
  {
    id: 'B06',
    number: 6,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'collaboration',
    prompt: 'question.B06.prompt',
    activeLearningEssentialTags: ['interdisciplinaryThinking'],
  },
  {
    id: 'B07',
    number: 7,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'problem',
    prompt: 'question.B07.prompt',
    activeLearningEssentialTags: ['problemSolving', 'valueAndAttitude'],
  },
  {
    id: 'B08',
    number: 8,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'design',
    prompt: 'question.B08.prompt',
    activeLearningEssentialTags: ['designAndInnovation', 'problemSolving'],
  },
  {
    id: 'B09',
    number: 9,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'planning',
    prompt: 'question.B09.prompt',
    activeLearningEssentialTags: ['problemSolving'],
  },
  {
    id: 'B10',
    number: 10,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'pitch',
    prompt: 'question.B10.prompt',
    activeLearningEssentialTags: ['communication', 'valueAndAttitude'],
  },
  {
    id: 'B11',
    number: 11,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'design',
    prompt: 'question.B11.prompt',
    activeLearningEssentialTags: ['designAndInnovation', 'lifelongLearning'],
  },
  {
    id: 'B12',
    number: 12,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'collaboration',
    prompt: 'question.B12.prompt',
    activeLearningEssentialTags: [
      'interdisciplinaryThinking',
      'valueAndAttitude',
    ],
  },
  {
    id: 'B13',
    number: 13,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'planning',
    prompt: 'question.B13.prompt',
    activeLearningEssentialTags: ['problemSolving', 'valueAndAttitude'],
  },
  {
    id: 'B14',
    number: 14,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'problem',
    prompt: 'question.B14.prompt',
    activeLearningEssentialTags: ['problemSolving'],
  },
  {
    id: 'B15',
    number: 15,
    phase: 'behaviour',
    kind: 'behaviour',
    competency: 'pitch',
    prompt: 'question.B15.prompt',
    activeLearningEssentialTags: ['communication', 'valueAndAttitude'],
  },
  {
    id: 'T01',
    number: 16,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'mechanical',
    prompt: 'question.T01.prompt',
  },
  {
    id: 'T02',
    number: 17,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'cad',
    prompt: 'question.T02.prompt',
  },
  {
    id: 'T03',
    number: 18,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'fabrication',
    prompt: 'question.T03.prompt',
  },
  {
    id: 'T04',
    number: 19,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'electronics',
    prompt: 'question.T04.prompt',
  },
  {
    id: 'T05',
    number: 20,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'programming',
    prompt: 'question.T05.prompt',
    activeLearningEssentialTags: ['lifelongLearning'],
  },
  {
    id: 'T06',
    number: 21,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'physicalComputing',
    prompt: 'question.T06.prompt',
  },
  {
    id: 'T07',
    number: 22,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'sensorsIot',
    prompt: 'question.T07.prompt',
  },
  {
    id: 'T08',
    number: 23,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'aiVision',
    prompt: 'question.T08.prompt',
    activeLearningEssentialTags: ['designAndInnovation', 'lifelongLearning'],
  },
  {
    id: 'T09',
    number: 24,
    phase: 'technical',
    kind: 'technical',
    toolkit: 'integration',
    prompt: 'question.T09.prompt',
    helper: 'question.T09.helper',
    activeLearningEssentialTags: [
      'designAndInnovation',
      'interdisciplinaryThinking',
    ],
  },
  {
    id: 'C01',
    number: 25,
    phase: 'context',
    kind: 'context',
    prompt: 'question.C01.prompt',
    helper: 'question.C01.helper',
    options: projectCountOptions,
  },
  {
    id: 'C02',
    number: 26,
    phase: 'context',
    kind: 'context',
    prompt: 'question.C02.prompt',
    options: responsibilityOptions,
  },
  {
    id: 'J01',
    number: 27,
    phase: 'judgment',
    kind: 'judgment',
    prompt: 'question.J01.prompt',
    options: [
      {
        id: 'adjust',
        label: 'question.J01.options.adjust.label',
        value: 1,
      },
      {
        id: 'replace',
        label: 'question.J01.options.replace.label',
        value: 2,
      },
      {
        id: 'repeat',
        label: 'question.J01.options.repeat.label',
        value: 3,
      },
      {
        id: 'isolate',
        label: 'question.J01.options.isolate.label',
        value: 4,
      },
      {
        id: 'diagnose',
        label: 'question.J01.options.diagnose.label',
        value: 5,
      },
    ],
    activeLearningEssentialTags: ['problemSolving', 'lifelongLearning'],
  },
  {
    id: 'J02',
    number: 28,
    phase: 'judgment',
    kind: 'judgment',
    prompt: 'question.J02.prompt',
    options: [
      {
        id: 'hide',
        label: 'question.J02.options.hide.label',
        value: 1,
      },
      {
        id: 'repeat-win',
        label: 'question.J02.options.repeat-win.label',
        value: 2,
      },
      {
        id: 'continue',
        label: 'question.J02.options.continue.label',
        value: 3,
      },
      {
        id: 'review',
        label: 'question.J02.options.review.label',
        value: 4,
      },
      {
        id: 'decide',
        label: 'question.J02.options.decide.label',
        value: 5,
      },
    ],
    activeLearningEssentialTags: ['valueAndAttitude', 'designAndInnovation'],
  },
  {
    id: 'I01',
    number: 29,
    phase: 'priorities',
    kind: 'interest',
    prompt: 'question.I01.prompt',
    helper: 'question.I01.helper',
    options: interestOptions,
    min: 0,
  },
  {
    id: 'G01',
    number: 30,
    phase: 'priorities',
    kind: 'growth',
    prompt: 'question.G01.prompt',
    helper: 'question.G01.helper',
    options: growthOptions,
    min: 1,
    activeLearningEssentialTags: ['lifelongLearning'],
  },
];
